name: Build OS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y nasm gcc make binutils

    - name: Build OS
      run: make

    - name: Upload IMG
      uses: actions/upload-artifact@v4
      with:
        name: os-image
        path: *.img
